# java -jar myapp.jar --debug
# 默认情况下，记录ERROR级、WARN级和INFO级消息。您还可以通过使用--debug标志启动应用程序来启用“调试”模式
# 您还可以在 application.yaml 中指定 debug=true。
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.logging
# debug: true


spring:
  profiles:
    # java -jar app.jar --spring.profiles.active=prod
    # jar 包命令行高于虚拟机参数指定高于 yaml 配置参数指定
    active: dev
  # https://docs.spring.io/spring-boot/docs/current/reference/html/data.html#data  
  # https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-access
  datasource:
    # MySQL5 : com.mysql.jdbc.Driver，
    # MySQL6 : com.mysql.cj.jdbc.Driver。
    # driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3306/db_dev"
    username: "root"
    password: "363636"
    
    # 连接池(默认: hikari)
    # type: com.zaxxer.hikari.HikariDataSource
    # Druid
    # hikari:
      # pool-name: "hikari-name"
    
    # Druid
    # https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      name: "druid-name"
      # Spring 监控( 依赖 spring-boot-starter-aop),多个用逗号分割
      # 需要 手动 配置 spring.aop.auto= false
      aop-patterns: "com.example.springbootlab.*.api.*"
      filter:
        stat:
          # SQL 监控配置
          enabled: true
        wall:
          # SQL 防火墙配置
          enabled: true
        slf4j:
          # Druid 日志配置
          enabled: true
      web-stat-filter:
        enabled: true
        # 排除路径
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
        # 开启session统计
        session-stat-enable: true
        
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: druid
        login-password: druid
  aop:
    auto: false



# sql 输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml 

server:
  port: 8080
dev:
  config:
    level: 100


logging:
  # https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.logging.custom-log-configuration
  # 二者不能同时使用，如若同时使用，则只有 logging.file 生效
  # logging.file.name or logging.file.path
  #  file:
  #    name: app.log
  #    path: ./logs
  #  level:
  #    root: info
  #    com: 
  #      example: info
  # file表示项目路径: /    
  # classpath表示资源路径: src/main/resources/
  config: classpath:logback-spring-full.xml

---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod
